// Code generated by GG version . DO NOT EDIT.

//go:build !gg
// +build !gg

package component

import app "github.com/maxence-charriere/go-app/v9/pkg/app"

func (c *CommandPalette) Render() app.UI {
	if cc, ok := any(c).(interface {
		OnBeforeRender()
	}); ok {
		cc.OnBeforeRender()
	}
	return app.Div().Class("relative z-10").Role("dialog").Aria("modal", "true").Body(app.Div().Class("fixed inset-0 bg-gray-500 bg-opacity-25 transition-opacity"), app.Div().Class("fixed inset-0 z-10 w-screen overflow-y-auto p-4 sm:p-6 md:p-20").Body(app.Div().Class("mx-auto max-w-xl transform divide-y divide-gray-100 overflow-hidden rounded-xl bg-white shadow-2xl ring-1 ring-black ring-opacity-5 transition-all").Body(app.Div().Class("relative").Body(app.Raw("<svg class=\"pointer-events-none absolute left-4 top-3.5 h-5 w-5 text-gray-400\" viewBox=\"0 0 20 20\" fill=\"currentColor\" aria-hidden=\"true\"><path fill-rule=\"evenodd\" d=\"M9 3.5a5.5 5.5 0 100 11 5.5 5.5 0 000-11zM2 9a7 7 0 1112.452 4.391l3.328 3.329a.75.75 0 11-1.06 1.06l-3.329-3.328A7 7 0 012 9z\" clip-rule=\"evenodd\"></path></svg>"), app.Input().Type("text").Class("h-12 w-full border-0 bg-transparent pl-11 pr-4 text-gray-900 placeholder:text-gray-400 focus:ring-0 sm:text-sm").Placeholder("Search...").Role("combobox").Aria("expanded", "false").Aria("controls", "options")), app.Ul().Class("max-h-72 scroll-py-2 overflow-y-auto py-2 text-sm text-gray-800").ID("options").Role("listbox").Body(app.Li().Class("cursor-default select-none px-4 py-2").ID("option-1").Role("option").TabIndex(-1).Body(app.Text("Leslie Alexander")), app.Li().Class("cursor-default select-none px-4 py-2").ID("option-2").Role("option").TabIndex(-1).Body(app.Text("Michael Foster")), app.Li().Class("cursor-default select-none px-4 py-2").ID("option-3").Role("option").TabIndex(-1).Body(app.Text("Dries Vincent")), app.Li().Class("cursor-default select-none px-4 py-2").ID("option-4").Role("option").TabIndex(-1).Body(app.Text("Lindsay Walton")), app.Li().Class("cursor-default select-none px-4 py-2").ID("option-5").Role("option").TabIndex(-1).Body(app.Text("Courtney Henry"))), app.P().Class("p-4 text-sm text-gray-500").Body(app.Text("No people found.")))))
}
