// Code generated by GG version . DO NOT EDIT.

//go:build !gg
// +build !gg

package component

import app "github.com/maxence-charriere/go-app/v9/pkg/app"

func (c *Settings) Render() app.UI {
	if cc, ok := any(c).(interface {
		OnBeforeRender()
	}); ok {
		cc.OnBeforeRender()
	}
	return
}
