// Code generated by GG version . DO NOT EDIT.

//go:build !gg
// +build !gg

package component

import app "github.com/maxence-charriere/go-app/v9/pkg/app"

func (c *Settings) Render() app.UI {
	if cc, ok := any(c).(interface {
		OnBeforeRender()
	}); ok {
		cc.OnBeforeRender()
	}
	return app.Div().Body(app.Div().Class("foo").Body(app.Text("Test")), app.Ul().Body(app.Range(c.items).Slice(func(i int) app.UI {
		return app.Li().Body(app.Ul().Body(app.Range(c.items[i].children).Slice(func(j int) app.UI {
			return app.Li().Body(app.Textf("vddb %s", c.items[i].children[j]))
		})))
	})), app.Ul().Body(app.Range(c.itemMap).Map(func(key string) app.UI {
		return app.Li().Body(app.Text("{itemMap[key]}"))
	})), app.If(c.isOk, app.P().Body(app.Text("hello"))), app.P().Body(app.Textf("Просто текст который мы отобразим - %s.", c.title)), app.P().Body(app.Textf("Число - %d", c.num)), app.P().Body(app.Textf("%s", c.test)), app.P().Body(app.Text("Небо – это бескрайняя панорама, простирающаяся над нами, словно величественное полотно, расписанное невидимыми кистями божественного художника. Оно – неизменный актёр на сцене нашей жизни, удивляющий нас своей переменчивостью и красотой.")), app.P().Body(app.Text("Утром, пробуждаясь от сна, мы смотрим на его нежно-розоватое платье, в котором противоборствуют сонные тени и проблески зари. Плотные тучи начинают таять под нежными лучами восходящего солнца, раскрывая дорогу синеве бегущих облаков. Небо, словно покрытое вуалью, создаёт атмосферу ожидания и свежести нового дня.")), app.P().Body(app.Text("В полдень небо превращается в бесконечный лазурный ковёр, которому нет предела. Пронизывающие солнечные лучи отражаются в лазурной глубине, как будто растворяются в нём, создавая иллюзию непостижимой границы. В этот момент, погружённые в фантазии, мы задумываемся о загадках вселенной и наших местах в этом бесконечном мире.")), app.P().Body(app.Textf("С приближением вечера небо меняется, будто переодевается в новые одежды. Очертания %s мягко окрашиваются розовым, переходя в оранжевый покрывало заката. Словно призрачные акварельные мазки, облака играют с цветами, рассыпаясь по небу в тысячи нежных оттенков. В этот момент мы чувствуем непостижимое притяжение к таинственному загадочному красоте пылающего небосвода.", c.title)))
}
