package file

import (
	"bytes"
	"path"
	"path/filepath"
	"strings"

	"github.com/555f/gg/pkg/types"

	"github.com/dave/jennifer/jen"
)

var _ File = &GoFile{}

type GoFile struct {
	*jen.File
	version     string
	path        string
	packagePath string
	module      *types.Module
}

func (f *GoFile) SetVersion(version string) {
	f.version = version
}

func (f *GoFile) IsCurrPkg(pkgPath string) bool {
	return path.Join(f.module.Path, f.packagePath) == pkgPath
}

func (f *GoFile) Qual(pkgPath, name string) func(s *jen.Statement) {
	return func(s *jen.Statement) {
		if f.IsCurrPkg(pkgPath) {
			s.Id(name)
		} else {
			s.Qual(pkgPath, name)
		}
	}
}

func (f *GoFile) Import(pkgPath, name string) func(s *jen.Statement) {
	return f.Qual(pkgPath, name)
}

func (f *GoFile) Filepath() string {
	return f.path
}

func (f *GoFile) PackagePath() string {
	return f.packagePath
}

func (f *GoFile) Bytes() ([]byte, error) {
	f.HeaderComment("Code generated by GG version " + f.version + ". DO NOT EDIT.")
	f.PackageComment("+build !gg")
	var buf bytes.Buffer
	if err := f.Render(&buf); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

func NewGoFile(module *types.Module, path string) *GoFile {
	parts := strings.Split(filepath.Dir(path), string(filepath.Separator))
	packagePath := parts[len(parts)-1]
	return &GoFile{File: jen.NewFilePath(packagePath), packagePath: packagePath, path: path, module: module}
}
