// Code generated by GG version . DO NOT EDIT.

//go:build !gg
// +build !gg

package middleware

import (
	controller "github.com/555f/gg/examples/grpc-service/internal/usecase/controller"
	dto "github.com/555f/gg/examples/grpc-service/pkg/dto"
	"time"
)

type ProfileControllerMiddleware func(controller.ProfileController) controller.ProfileController

func ProfileControllerMiddlewareChain(outer ProfileControllerMiddleware, others ...ProfileControllerMiddleware) ProfileControllerMiddleware {
	return func(next controller.ProfileController) controller.ProfileController {
		for i := len(others) - 1; i >= 0; i-- {
			next = others[i](next)
		}
		return outer(next)
	}
}

type profileControllerBaseMiddleware struct {
	next     controller.ProfileController
	mediator any
}

func (m *profileControllerBaseMiddleware) Create(token string, firstName string, lastName string, address string, old int, age time.Time, sleep time.Duration) (profile *dto.Profile, err error) {
	defer func() {
		if s, ok := m.mediator.(profileControllerCreateBaseMiddleware); ok {
			s.Create(token, firstName, lastName, address, old, age, sleep)
		}
	}()
	return m.next.Create(token, firstName, lastName, address, old, age, sleep)
}
func (m *profileControllerBaseMiddleware) Remove(id string) (err error) {
	defer func() {
		if s, ok := m.mediator.(profileControllerRemoveBaseMiddleware); ok {
			s.Remove(id)
		}
	}()
	return m.next.Remove(id)
}
func (m *profileControllerBaseMiddleware) Stream(profile chan *dto.Profile) (statistics chan *dto.Statistic, err error) {
	defer func() {
		if s, ok := m.mediator.(profileControllerStreamBaseMiddleware); ok {
			s.Stream(profile)
		}
	}()
	return m.next.Stream(profile)
}
func (m *profileControllerBaseMiddleware) Stream2(profile chan *dto.Profile) (err error) {
	defer func() {
		if s, ok := m.mediator.(profileControllerStream2BaseMiddleware); ok {
			s.Stream2(profile)
		}
	}()
	return m.next.Stream2(profile)
}
func (m *profileControllerBaseMiddleware) Stream3(profile *dto.Profile) (statistics chan *dto.Statistic, err error) {
	defer func() {
		if s, ok := m.mediator.(profileControllerStream3BaseMiddleware); ok {
			s.Stream3(profile)
		}
	}()
	return m.next.Stream3(profile)
}
func (m *profileControllerBaseMiddleware) Update(profile dto.Profile) (err error) {
	defer func() {
		if s, ok := m.mediator.(profileControllerUpdateBaseMiddleware); ok {
			s.Update(profile)
		}
	}()
	return m.next.Update(profile)
}

type profileControllerCreateBaseMiddleware interface {
	Create(token string, firstName string, lastName string, address string, old int, age time.Time, sleep time.Duration)
}
type profileControllerRemoveBaseMiddleware interface {
	Remove(id string)
}
type profileControllerStreamBaseMiddleware interface {
	Stream(profile chan *dto.Profile)
}
type profileControllerStream2BaseMiddleware interface {
	Stream2(profile chan *dto.Profile)
}
type profileControllerStream3BaseMiddleware interface {
	Stream3(profile *dto.Profile)
}
type profileControllerUpdateBaseMiddleware interface {
	Update(profile dto.Profile)
}

func ProfileControllerBaseMiddleware(mediator any) ProfileControllerMiddleware {
	return func(next controller.ProfileController) controller.ProfileController {
		return &profileControllerBaseMiddleware{next: next, mediator: mediator}
	}
}
