// Code generated by GG version . DO NOT EDIT.

//go:build !gg

package client

const fooClientBarMethod = "(github.com/555f/gg/examples/metrics-middleware/internal/client.FooClient).BarMethod"
const fooClientBarMethodShort = "(client.FooClient).BarMethod"
