// Code generated by GG version . DO NOT EDIT.

//go:build !gg

package client

type FooClientMiddleware func(FooClient) FooClient

func FooClientMiddlewareChain(outer FooClientMiddleware, others ...FooClientMiddleware) FooClientMiddleware {
	return func(next FooClient) FooClient {
		for i := len(others) - 1; i >= 0; i-- {
			next = others[i](next)
		}
		return outer(next)
	}
}

type fooClientBaseMiddleware struct {
	next     FooClient
	mediator any
}

func (m *fooClientBaseMiddleware) BarMethod(test string) (n int, err error) {
	defer func() {
		if s, ok := m.mediator.(fooClientBarMethodBaseMiddleware); ok {
			s.BarMethod(test)
		}
	}()
	return m.next.BarMethod(test)
}

type fooClientBarMethodBaseMiddleware interface {
	BarMethod(test string)
}

func FooClientBaseMiddleware(mediator any) FooClientMiddleware {
	return func(next FooClient) FooClient {
		return &fooClientBaseMiddleware{next: next, mediator: mediator}
	}
}
